FROM python:3.6.8-jessie
ENV PYTHONUNBUFFERED 1
RUN printf "deb http://archive.debian.org/debian/ jessie main\ndeb-src http://archive.debian.org/debian/ jessie main\ndeb http://security.debian.org jessie/updates main\ndeb-src http://security.debian.org jessie/updates main" > /etc/apt/sources.list
RUN apt-get update && apt-get install -y \
    build-essential \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    liblcms2-dev \
    libmemcached-dev \
    libmysqlclient-dev \
    libtiff5-dev \
    libwebp-dev \
    libxslt1-dev \
    mysql-client \
    python-dev \
    tcl8.6-dev \
    tk8.6-dev
RUN pip install --upgrade pip
RUN mkdir -p /code
COPY requirements.txt /
RUN pip install -r requirements.txt
WORKDIR /code
