# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 22:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import isbn_field.fields
import isbn_field.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('isbn', isbn_field.fields.ISBNField(max_length=13, unique=True, validators=[isbn_field.validators.ISBNValidator], verbose_name='ISBN')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'books__book',
                'ordering': ['id'],
            },
        ),
    ]
