name: Python application

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    container: python:3.6.8-jessie
    services:
        postgres:
          image: postgres:10.8
          env:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
          ports:
          - 5432:5432
          # needed because the postgres container does not provide a healthcheck
          options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v1
    - name: upgrade package
      run: | 
        apt-get update && apt-get install -y build-essential
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with django test framework
      run: |
        python ./manage.py test
