name: Python application

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    container: python:3.6.8-jessie
    services:
        postgres:
          image: postgres:10.8
          env:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
          ports:
          - 5432:5432
          # needed because the postgres container does not provide a healthcheck
          options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v1
    - name: upgrade package
      run: | 
        printf "deb http://archive.debian.org/debian/ jessie main\ndeb-src http://archive.debian.org/debian/ jessie main\ndeb http://security.debian.org jessie/updates main\ndeb-src http://security.debian.org jessie/updates main" > /etc/apt/sources.list
        apt-get update && apt-get install -y \
            build-essential \
            libfreetype6-dev \
            libjpeg62-turbo-dev \
            liblcms2-dev \
            libmemcached-dev \
            libmysqlclient-dev \
            libtiff5-dev \
            libwebp-dev \
            libxslt1-dev \
            mysql-client \
            python-dev \
            tcl8.6-dev \
            tk8.6-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with django test framework
      run: |
        python ./manage.py test
